apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/yrj2011/jx-spring-17:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/yrj2011/jx-spring-17:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: jx-spring-17
        chartPath: charts/jx-spring-17
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/yrj2011/jx-spring-17'
          image.tag: '{{.DIGEST_HEX}}'
